<?php
namespace Magenest\Movie\Block\Adminhtml\Director;

class Grid extends \Magento\Backend\Block\Widget\Grid\Extended {
    protected $_directorCollection;
    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Backend\Helper\Data $backendHelper
     * @param \Magenest\Movie\Model\ResourceModel\Movie\Collection $movieCollection
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Magenest\Movie\Model\ResourceModel\Movie\Collection $directorCollection,
        array $data = []
    ){
        $this->_directorCollection = $directorCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__('No Director Found'));
    }
    /**
     * Initialize the movie collection
     *
     * @return WidgetGrid
     */
    protected function _prepareCollection(){
        $this->setCollection($this->_directorCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    /**
     * Prepare grid colums
     *
     * @return $this
     */
    protected function _prepareColumns(){
        $this->addColumn(
            'director_id',
            [
                'header' => __('Director'),
                'index' => 'director_id'
            ]
        );
        $this->addColumn(
            'name',
            [
                'header' => __('Name of Director'),
                'index' => 'name'
            ]
        );
        return $this;
    }
}