<?php
namespace Magenest\Movie\Block\Adminhtml\Actor;

class Grid extends \Magento\Backend\Block\Widget\Grid\Extended {
    protected $_actorCollection;
    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Backend\Helper\Data $backendHelper
     * @param \Magenest\Movie\Model\ResourceModel\Movie\Collection $movieCollection
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Magenest\Movie\Model\ResourceModel\Movie\Collection $actorCollection,
        array $data = []
    ){
        $this->_actorCollection = $actorCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__('No Actor Found'));
    }
    /**
     * Initialize the movie collection
     *
     * @return WidgetGrid
     */
    protected function _prepareCollection(){
        $this->setCollection($this->_actorCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    /**
     * Prepare grid colums
     *
     * @return $this
     */
    protected function _prepareColumns(){
        $this->addColumn(
            'actor_id',
            [
                'header' => 'Actor Id',
                'index' => 'actor_id'
            ]
        );
        $this->addColumn(
            'name',
            [
                'header' => 'Name of Actor',
                'index' => 'name'
            ]
        );
        return $this;
    }
}