<?php
namespace Magenest\Movie\Controller\Adminhtml\Movie;

use \Magento\Backend\App\Action\Context;
use \Magento\Framework\View\Result\PageFactory;

class Director extends \Magento\Backend\App\Action {
    protected $resultPageFactory;
    public function __construct(\Magento\Framework\App\Action\Context $context, \Magento\Framework\View\Result\PageFactory $resultPageFactory){
        $this->resultPageFactory = $resultPageFactory;
        parent::__construct($context);
    }
    public function execute(){
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('Magenest_Movie::director');
        $resultPage->addBreadcrumb(__('Director'), __('Director'));
        $resultPage->addBreadcrumb(__('Manage Director'), __('Manage Director'));
        $resultPage->getConfig()->getTitle()->prepend(__('Director'));
        return $resultPage;
    }
    public function _isAllowed(){
        return $this->_authorization->isAllowed('Magenest_Movie::director'); // TODO: Change the autogenerated stub
    }
}