<?php
namespace Magenest\Movie\Block\Adminhtml\MovieActor;

class Grid extends \Magento\Backend\Block\Widget\Grid\Extended {
    protected $_movieactorCollection;
    /**
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Backend\Helper\Data $backendHelper
     * @param \Magenest\Movie\Model\ResourceModel\Movie\Collection $movieactorCollection
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Backend\Helper\Data $backendHelper,
        \Magenest\Movie\Model\ResourceModel\Movie\Collection $movieactorCollection,
        array $data = []
    ){
        $this->_movieactorCollection = $movieactorCollection;
        parent::__construct($context, $backendHelper, $data);
        $this->setEmptyText(__('No Movie Actor Found'));
    }
    /**
     * Initialize the movie collection
     *
     * @return WidgetGrid
     */
    protected function _prepareCollection(){
        $this->setCollection($this->_movieactorCollection);
        return parent::_prepareCollection(); // TODO: Change the autogenerated stub
    }
    /**
     * Prepare grid colums
     *
     * @return $this
     */
    protected function _prepareColumns(){
        $this->addColumn(
            'movie_id',
            [
                'header' => 'Movie Id',
                'index' => 'movie_id'
            ]
        );
        $this->addColumn(
            'actor_id',
            [
                'header' => 'Actor Id',
                'index' => 'actor_id'
            ]
        );
        return $this;
    }
}