<h2>HelloWorld</h2>
<p>Table magenest_movie</p>

<?php
    $myData1 = $block->getCustomerDataInDatabase('magenest_movie');
    if(!empty($myData1)) {
?>
    <table>
        <tr>
            <th>Movie Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Rating</th>
            <th>Director</th>
        </tr>
        <?php foreach ($myData1 as $data): ?>
        <tr>
            <td><?= $data['movie_id'] ?></td>
            <td><?= $data['name'] ?></td>
            <td><?= $data['description'] ?></td>
            <td><?= $data['rating'] ?></td>
            <td><?= $data['director_id'] ?></td>
        </tr>
        <?php endforeach;?>
    </table>
<?php
    }else{
        echo "NO data";
    }
?>
<br/>
<p>Table magenest_actor</p>
<?php
    $myData2 = $block->getCustomerDataInDatabase('magenest_actor');
    if(!empty($myData2)){
?>
        <table>
            <tr>
                <th>Actor Id</th>
                <th>Name</th>
            </tr>
            <?php foreach ($myData2 as $data): ?>
                <tr>
                    <td><?= $data['actor_id'] ?></td>
                    <td><?= $data['name'] ?></td>
                </tr>
            <?php endforeach;?>
        </table>
<?php
    }else{
        echo "NO data";
    }
?>